In [54]:
import sklearn
from sklearn import datasets
## from sklearn import datasets which contains many predefined datasets that we can easily fetch and use if we want

In [55]:
dir(datasets)  ## this will shgow all the datasets,dir means directory

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'descr',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 '

In [56]:
## we want to access fetch_california_housing dataset
from sklearn.datasets import fetch_california_housing
california= fetch_california_housing()
california   ## as we can see kit is displayed in 2 dimentional format (one cannot understand it easily)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [57]:
california.keys()  ## as in a dictionary , keys can be denotted as columns

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [58]:
california.values() ## basically rows

dict_values([array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), None, ['MedHouseVal'], ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:*

In [59]:
## so now we create dataframe to visualize the dataset easily

In [60]:
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing (as_frame=True) # usaully it is false thus us showing the data in 2 dimentional format
california_df = california['frame']
california_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

**Method :**
**Feature Selection**

**Feature Selection and Feature scaling**

**VIF**

-- Seperate input Columns and output columns

In [61]:
x= california_df.drop('MedHouseVal',axis=1)  # input  , axis=0 means rows, axis =1 means columns
y= california_df['MedHouseVal']              # output

In [62]:
x

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [63]:
x.columns  ## creates a list of all the column names

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

In [64]:
x.rows  ## won't work it will show error because there is no attribute as rows in dataframe methoda

AttributeError: 'DataFrame' object has no attribute 'rows'

In [65]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

**Find the VIF**

In [66]:
# class----> statsmodels.stats.outliers_influence method
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data=[]   ## empty list  later used in a dataframe
for i in range(len(x.columns)):
    vif_data.append(variance_inflation_factor(x.values,i))   ## vifs are calculated and stored in empty list
vif_data   

[11.511140059486946,
 7.195917300645759,
 45.99360103802389,
 43.59031403163056,
 2.935745199687899,
 1.0952432155971747,
 559.8740713791312,
 633.7116543669108]

**Create Dataframe**

In [67]:
import pandas as pd
vif_df=pd.DataFrame(vif_data,index=x.columns,columns=['VIF'])  ## taking index as the input columns for better view
vif_df.sort_values(by='VIF',ascending=False)  ## just sorting the column VIF in descending order

VIF
Longitude   633.711654
Latitude    559.874071
AveRooms     45.993601
AveBedrms    43.590314
MedInc       11.511140
HouseAge      7.195917
Population    2.935745
AveOccup      1.095243

In [68]:
# till now we have seen that the dataframe method has index,the read datset, columns, axis as different attributes

**Select the Final columns**

In [69]:
con1 = vif_df[vif_df['VIF']<15].index
con1 = con1.to_list()
con1

['MedInc', 'HouseAge', 'Population', 'AveOccup']

In [70]:
b=vif_df[vif_df['VIF']>15].index
b

Index(['AveRooms', 'AveBedrms', 'Latitude', 'Longitude'], dtype='object')

In [71]:
con2 = ['AveBedrms','Latitude']
con2

['AveBedrms', 'Latitude']

In [72]:
final_cols=con1+con2
final_cols

['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveBedrms', 'Latitude']

**Created a Final DataFrame (VIF)**

In [73]:
import warnings
warnings.filterwarnings('ignore')
final_df=x[final_cols]
final_df['MedHouseVal']=y
final_df

MedInc  HouseAge  Population  AveOccup  AveBedrms  Latitude  \
0      8.3252      41.0       322.0  2.555556   1.023810     37.88   
1      8.3014      21.0      2401.0  2.109842   0.971880     37.86   
2      7.2574      52.0       496.0  2.802260   1.073446     37.85   
3      5.6431      52.0       558.0  2.547945   1.073059     37.85   
4      3.8462      52.0       565.0  2.181467   1.081081     37.85   
...       ...       ...         ...       ...        ...       ...   
20635  1.5603      25.0       845.0  2.560606   1.133333     39.48   
20636  2.5568      18.0       356.0  3.122807   1.315789     39.49   
20637  1.7000      17.0      1007.0  2.325635   1.120092     39.43   
20638  1.8672      18.0       741.0  2.123209   1.171920     39.43   
20639  2.3886      16.0      1387.0  2.616981   1.162264     39.37   

       MedHouseVal  
0            4.526  
1            3.585  
2            3.521  
3            3.413  
4            3.422  
...            ...  
20635        0.781  
20636        0.771  
20637        0.923  
20638        0.847  
20639        0.894  

[20640 rows x 7 columns]

In [74]:
X=final_df.drop('MedHouseVal',axis=1)
Y=final_df['MedHouseVal']

In [75]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_scale=ss.fit_transform(X)
x_scale

array([[ 2.34476576,  0.98214266, -0.9744286 , -0.04959654, -0.15375759,
         1.05254828],
       [ 2.33223796, -0.60701891,  0.86143887, -0.09251223, -0.26333577,
         1.04318455],
       [ 1.7826994 ,  1.85618152, -0.82077735, -0.02584253, -0.04901636,
         1.03850269],
       ...,
       [-1.14259331, -0.92485123, -0.3695372 , -0.0717345 ,  0.04941393,
         1.77823747],
       [-1.05458292, -0.84539315, -0.60442933, -0.09122515,  0.15877763,
         1.77823747],
       [-0.78012947, -1.00430931, -0.03397701, -0.04368215,  0.1384028 ,
         1.75014627]])

**Created a Scale DF**

In [76]:
x_scale_df=pd.DataFrame(x_scale,columns=X.columns)
x_scale_df

MedInc  HouseAge  Population  AveOccup  AveBedrms  Latitude
0      2.344766  0.982143   -0.974429 -0.049597  -0.153758  1.052548
1      2.332238 -0.607019    0.861439 -0.092512  -0.263336  1.043185
2      1.782699  1.856182   -0.820777 -0.025843  -0.049016  1.038503
3      0.932968  1.856182   -0.766028 -0.050329  -0.049833  1.038503
4     -0.012881  1.856182   -0.759847 -0.085616  -0.032906  1.038503
...         ...       ...         ...       ...        ...       ...
20635 -1.216128 -0.289187   -0.512592 -0.049110   0.077354  1.801647
20636 -0.691593 -0.845393   -0.944405  0.005021   0.462365  1.806329
20637 -1.142593 -0.924851   -0.369537 -0.071735   0.049414  1.778237
20638 -1.054583 -0.845393   -0.604429 -0.091225   0.158778  1.778237
20639 -0.780129 -1.004309   -0.033977 -0.043682   0.138403  1.750146

[20640 rows x 6 columns]

**Method : Train Test Split**

- Package name : sklearn
 - class name   : model_selection
 - Method Name  : Train_Test_split

In [77]:
from sklearn.model_selection import train_test_split
# Train the Model

x_train,x_test,y_train,y_test=train_test_split(x_scale_df,
                                              Y,
                                              test_size=0.2,
                                              random_state=1234)

**CheckPoint - 1**

- original data shape 
- x_train shape and x_test shape
- check the rows and columns

In [78]:
x_scale_df.shape,x_train.shape,x_test.shape

((20640, 6), (16512, 6), (4128, 6))

**Checkpoint - 2**

- x_train rows should match with y_train rows count
- x_test rows should match with y_test rows count 

In [79]:
x_train.shape , y_train.shape

((16512, 6), (16512,))

In [80]:
x_test.shape , y_test.shape

((4128, 6), (4128,))

**Checkpoint - 3**

- read the x_train and y_train and check the index

In [81]:
x_train.index

Index([17595,  6073,  6251,  3161,  1887,   151,  8888,  6273,  7383, 19964,
       ...
       13686,  7962,  8060,  7916,  1182,  8222,  9449,  8471, 17048,  1318],
      dtype='int64', length=16512)

In [82]:
y_train.index

Index([17595,  6073,  6251,  3161,  1887,   151,  8888,  6273,  7383, 19964,
       ...
       13686,  7962,  8060,  7916,  1182,  8222,  9449,  8471, 17048,  1318],
      dtype='int64', length=16512)

**Method : Model developnment**
- model develop by only train data
  - package name : sklearn
  - Class Name : linear_model
  - method Name : LinearRegression

In [83]:
from sklearn.linear_model import LinearRegression
# train the model 

lr_model = LinearRegression()
lr_model.fit(x_train , y_train)

LinearRegression()

**Method : Model Predictions**

In [84]:
# predicts on test data 
y_pred = lr_model.predict(x_test)
y_pred

array([2.29641648, 3.29188843, 2.22965756, ..., 1.38404565, 2.36558921,
       1.69402488])

-Just Drilling  (just checking)

In [85]:
len(x_test)

4128

In [86]:
len(y_pred)

4128

In [87]:
lr_model.coef_  # slope

array([ 0.8120885 ,  0.23134594,  0.02939056, -0.04494048,  0.01445806,
       -0.09962109])

In [88]:
lr_model.intercept_  # error b0

2.064433484817849

In [89]:
X.columns

Index(['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveBedrms',
       'Latitude'],
      dtype='object')

In [90]:
x_test.values[0]

array([-0.09973335,  1.85618152, -0.71657708, -0.1295939 , -0.03803226,
        1.01041149])

In [91]:
import numpy as np 
lr_model.intercept_+np.sum(lr_model.coef_*x_test.values[0])

2.2964164797983457

In [92]:
x_test.values[0]

array([-0.09973335,  1.85618152, -0.71657708, -0.1295939 , -0.03803226,
        1.01041149])

In [93]:
import numpy as np 
lr_model.intercept_+np.sum(lr_model.coef_*x_test.values[0])

2.2964164797983457

In [94]:
x_test
# update the table 
# add a extra columns as y_actual = y_test is the data 
# add an extra columns name as y_prediction   = y_prediction is the data

MedInc  HouseAge  Population  AveOccup  AveBedrms  Latitude
15712 -0.099733  1.856182   -0.716577 -0.129594  -0.038032  1.010411
4119   0.885225  1.856182    0.367812 -0.009598  -0.115509 -0.698469
15725  0.002279  1.220517   -0.763379 -0.129966  -0.152216  1.005730
14616 -0.210589 -0.686477    0.350151  0.031639  -0.133136 -1.325839
13238  2.027992 -1.481058   -0.180564  0.035508  -0.162391 -0.703151
...         ...       ...         ...       ...        ...       ...
13521  0.703519 -0.686477   -0.779274 -0.017558  -0.282569 -0.651651
16913  5.011449 -0.289187    0.071989 -0.007758  -0.145384  0.898047
20069 -0.699541  0.108104   -1.045073 -0.045110   0.159038  1.113413
446    0.002279  1.856182   -0.917913 -0.113472  -0.266063  1.047866
2209  -0.060887 -1.083767   -0.366005  0.003862  -0.301391  0.551589

[4128 rows x 6 columns]

In [95]:
## Defining eval_df (Fixing the previous error)

eval_df = pd.DataFrame({
    'Y_actual': y_test.values,
    'Y_prediction': y_pred
})


In [96]:
x_train , x_test , y_train , y_test = train_test_split(x_scale_df,
                                                       y , 
                                                       test_size = 0.2,
                                                       random_state = 1234)
# add extra columns Y_actual and Y-Prediction 
eval_df['Y_actual'] = y_test
eval_df['Y_prdeiction']=y_pred
# add extra columns error , msc , rmse 
eval_df['Error']=eval_df['Y_actual']-eval_df['Y_prdeiction']
eval_df['Error_square']=eval_df['Error']**2
mse =np.sum(eval_df['Error_square'])/len(x_test)
rmse =np.sqrt(mse)
print('MSE :' ,mse)
print('RMSE :',rmse)

MSE : 0.3704727466985432
RMSE : 0.6086647243750398


In [97]:
np.sum(np.square(eval_df['Y_actual'].values - eval_df['Y_prdeiction'].values))/len(eval_df)

nan

In [98]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

0.6619661531094175

In [99]:
np.sum(np.square(eval_df['Y_actual'].values - eval_df['Y_prdeiction'].values))/len(eval_df)

nan

## fixing saving error

In [100]:
# Save model correctly
with open('Linear_Regression_California.pkl', 'wb') as f:
    pickle.dump(lr_model, f)

In [101]:
# Load model to verify
with open('Linear_Regression_California.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

print("Model loaded successfully:", loaded_model)


Model loaded successfully: LinearRegression()


# Don't run this it will cause error

**Save The Model**

- using pickle
- open('File_name.txt','w')
- pickle.dump(model_name , w')

In [46]:
import pickle
path = open('Linear_Regression_california.pkl','wb')
pickle.dump(lr_model,path)

In [47]:
with open('Linear_regressio_california.pkl','wb') as file:
    pickle.dump(lr_model,file)

**Load the Model**

- pickle.load(path,'rb')

In [48]:
load_model=pickle.load(open('Linear_regressio_california.pkl','rb'))
load_model

LinearRegression()

In [49]:
path = open('Linear_regressio_california.pkl','rb')
loaded_model = pickle.load(path)
loaded_model

LinearRegression()

**Predict Test Data**

In [50]:
len(x_test.values[0])
# load_model.predict(x_test)

6

In [51]:
load_model.predict([x_test.values[0]])

array([2.29641648])

**That's Why first check the model colums**

In [52]:
load_model.predict([[1,2,3,4,5,6]])

array([2.72218737])

In [53]:
load_model.predict(x_test)

array([2.29641648, 3.29188843, 2.22965756, ..., 1.38404565, 2.36558921,
       1.69402488])